extends: 
  - "plugin:vue/base"
  - "plugin:vue/recommended"
rules:
  semi:
    - error
    - never
parser: 'vue-eslint-parser'
parserOptions:
  parser: "babel-eslint"
  sourceType: 'module'
  allowImportExportEverywhere: true
